version: '3.9'
services: 
  db:
    image: postgres:15
    container_name: postgressDB_wendy
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: bdusuarios_wendy
    ports:
      - "5438:5432"
    volumes:
      - "./data_wendy:/var/lib/postgresql/data"
